---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fake-dcgm-exporter-config
  namespace: monitoring
data:
  config.yaml: |
    modelName: NVIDIA A100-SXM4-40GB
    driverVersion: "535.104.12"
    port: 9400
    number: 8

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: fake-dcgm-exporter
    app.kubernetes.io/instance: fake-dcgm-exporter
    app.kubernetes.io/name: fake-dcgm-exporter
  name: fake-dcgm-exporter
  namespace: monitoring
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: dcgm-exporter
      app.kubernetes.io/instance: dcgm-exporter
      app.kubernetes.io/name: dcgm-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: dcgm-exporter
        app.kubernetes.io/instance: dcgm-exporter
        app.kubernetes.io/name: dcgm-exporter
    spec:
      containers:
      - name: dcgm-exporter
        image: crazytaxii/fake-dcgm-exporter:latest
        imagePullPolicy: Always
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        volumeMounts:
        - name: config-vol
          mountPath: /etc/fake-dcgm-exporter
          readOnly: true
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 9400
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 9400
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 9400
          name: metrics
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: config-vol
        configMap:
          name: fake-dcgm-exporter-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: dcgm-exporter
    app.kubernetes.io/instance: dcgm-exporter
  name: dcgm-exporter
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9400
    protocol: TCP
    targetPort: 9400
  selector:
    app.kubernetes.io/instance: dcgm-exporter
    app.kubernetes.io/name: dcgm-exporter
  sessionAffinity: None
